cask_args appdir: "/Applications"

tap "caskroom/cask"

brew "fasd"
brew "git"
brew "gnupg"
brew "hub"
brew "imagemagick"
brew "mas"
brew "puma-dev"
brew "rbenv"
brew "ruby-build"
brew "the_silversearcher"
brew "tmux"
brew "tree"
brew "vim"
brew "zsh"

cask "1password"
cask "1password-cli"
cask "adobe-creative-cloud"
cask "alfred"
cask "bartender"
cask "appcleaner"
cask "boom-3d"
cask "fork"
cask "fromscratch"
cask "iterm2"
cask "karabiner-elements"
cask "keybase"
cask "postico"
cask "slack"
cask "spectacle"
cask "spotify"
cask "textmate"

mas "Bear", id: 1091189122
mas "Things3", id: 904280696
mas "Shush", id: 496437906

