# Executes commands at the start of an interactive session.

# Use a super basic prompt configuration
export PROMPT="%F{green}$%f "

# Other components
source "$HOME/.zsh/components/zshrc/vi-mode.zsh"
source "$HOME/.zsh/components/zshrc/fasd.zsh"
source "$HOME/.zsh/components/zshrc/fzf.zsh"
source "$HOME/.zsh/components/zshrc/ruby.zsh"
source "$HOME/.zsh/components/zshrc/git.zsh"
source "$HOME/.zsh/components/zshrc/history.zsh"
source "$HOME/.zsh/components/zshrc/tmux.zsh"
source "$HOME/.zsh/components/zshrc/k.zsh"
source "$HOME/.zsh/components/zshrc/weather.zsh"

# Local customizations, secrets, etc.
if [[ -r "$HOME/.zshlc" ]]; then
  source "$HOME/.zshlc"
fi

# Misc
alias scotty_joke_funny="ruby -e 'puts %(#scottyjoke is #{ [true,false,false,false,false].sample ? nil : %(not ) }funny.)'"

