#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Phillip Ridlen <p@rdln.net>
#

#
# Source Prezto.
#
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# Source Boxen
#
if [[ -d /opt/boxen ]]
then
  source /opt/boxen/env.sh
fi


#
# Luigi
#
#tart bake $HOME/luigi.tart

#
# AutoJump
#
type brew &> /dev/null && [[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

#
# Aliases
#
alias b='bundle exec'

alias migrate="rake db:migrate"
alias rollback="rake db:rollback"

alias frails="foreman run bundle exec rails"
alias frake="foreman run bundle exec rake"
alias fresq="foreman run bundle exec rake jobs:work"

alias cuke="cucumber"

alias git="nocorrect git"
alias gglg="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --"
alias gst="git status -sb"
alias gcb="git rev-parse --abbrev-ref HEAD"
alias ggpush="git push origin \`gcb\`"
alias gd="git difftool"

alias s='subl'

# Quick way to rebuild the Launch Services database and get rid
# of duplicates in the Open With submenu.
alias fixopenwith='/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user'
