" Pathogen '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
execute pathogen#infect()

" Basics '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
syntax on
filetype plugin indent on
set mouse=a
set noswapfile
set nobackup
set nowb
set visualbell
set laststatus=2
set number
et dir=~/.vim/swap//,/var/tmp//,/tmp//,.

" Tabs
set softtabstop=2
set shiftwidth=2
set tabstop=2
set expandtab

" Keys '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
let mapleader = ','

nmap <Leader>n :NERDTreeToggle<CR>
nmap <Leader>t <C-p>


" Colors '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
colorscheme solarized
set background=dark
set colorcolumn=80

" Set vertical fillchar to "en space"
set fillchars+=vert: 

" Powerline ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
let g:Powerline_symbols = 'fancy'

" CtrlP ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
let g:ctrlp_custom_ignore = {
  \ 'dir': 'vendor/bundle'
  \ }

" BufferGator ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
let g:buffergator_viewport_split_policy = "T"
let g:buffergator_viewport_sort_regime = "mru"
let g:buffergator_split_size = 20

" NERDTree '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
let NERDTreeQuitOnOpen = 1
let NERDTreeShowHidden = 1

" File types '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
" associate *.brs (BrightScript) with vb filetype
au BufRead,BufNewFile *.brs setfiletype vb

