"═ Initial setup ══════════════════════════════════════════════════════════════════════════════════

  " use Vim settings, rather than Vi settings
  set nocompatible

  " initialize pathogen and rebuild helptags
  execute pathogen#infect()
  execute pathogen#helptags()

"═ Basics ═════════════════════════════════════════════════════════════════════════════════════════

  syntax on

  set number                    " display line numbers
  set laststatus=2              " show status bar
  set mouse=a                   " allow mouse usage
  set noswapfile                " don't create swap files
  set nobackup                  " don't create backup files
  set undodir=~/.vim/undo//     " put undo files in ~/.vim/undo/path%to$file.ext
  set nowb                      " don't wub wub wub
  set visualbell                " use vilsual bell

  filetype plugin on
  filetype indent on

  " Tabs & Indentation
  set autoindent
  set smartindent
  set smarttab
  set softtabstop=2
  set shiftwidth=2
  set tabstop=2
  set expandtab

  " Line Wrapping
  set nowrap
  set linebreak

  " Auto View Scrolling
  set scrolloff=8       " start scrolling 8 lines from bottom
  set sidescrolloff=15  " start scrolling 15 lines from right

"═ Keys ═══════════════════════════════════════════════════════════════════════════════════════════

  let mapleader = ','

  nmap <Leader>n :NERDTreeToggle<CR>
  nmap <Leader>p <C-p>


"═ Theme ══════════════════════════════════════════════════════════════════════════════════════════

  colorscheme solarized
  set background=dark
  set colorcolumn=100

  set fillchars+=vert:                    " Set vertical fillchar to "en space"

  set list listchars=tab:\ \ ,trail:•     " Use "\ \ " for tabs and "•" for
                                          " trailing spaces

"═ CtrlP ══════════════════════════════════════════════════════════════════════════════════════════

  let g:ctrlp_custom_ignore = {
    \ 'dir': 'vendor/bundle'
    \ }

"═ BufferGator ════════════════════════════════════════════════════════════════════════════════════

  let g:buffergator_viewport_split_policy = "T"    " split to top
  let g:buffergator_viewport_sort_regime = "mru"   " sort by 'most recently used'
  let g:buffergator_split_size = 10

"═ NERDTree ═══════════════════════════════════════════════════════════════════════════════════════
" NERDTree '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

  let NERDTreeQuitOnOpen = 1  " Hide NERDTree when opening a file
  let NERDTreeShowHidden = 0  " Don't show hidden files

"═ File Types ═════════════════════════════════════════════════════════════════════════════════════

  au BufRead,BufNewFile *.brs setfiletype vb  " BrightScript

