name: Installation Smoke Test

on: [push]

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          path: "dotfiles-files"
      - name: Run install script
        run: "source ./dotfiles-files/.local/dotfiles/lib/dot.zsh && dot::install"
        shell: zsh -c {0}
